module.exports = {
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        noir: 'var(--color-noir)',
        blanc: 'var(--color-blanc)',
        or: 'var(--color-or)',
        'gris-light': 'var(--color-gris-light)',
        'gris-medium': 'var(--color-gris-medium)',
        'gris-dark': 'var(--color-gris-dark)',
        success: 'var(--color-success)',
        warning: 'var(--color-warning)',
        error: 'var(--color-error)',
        info: 'var(--color-info)',
      },
      spacing: {
        '4': '4px',
        '8': '8px',
        '12': '12px',
        '16': '16px',
        '20': '20px',
        '24': '24px',
        '32': '32px',
        '40': '40px',
        '48': '48px',
        '56': '56px',
        '64': '64px',
        '72': '72px',
        '80': '80px',
        '96': '96px',
        '120': '120px',
      },
      aspectRatio: {
        'product': '4 / 5',
        'hero': '16 / 9',
        'square': '1 / 1',
        'wide': '21 / 9',
      },
      boxShadow: {
        'sm': '0 1px 2px rgba(0, 0, 0, 0.05)',
        'md': '0 4px 6px rgba(0, 0, 0, 0.1)',
        'lg': '0 10px 15px rgba(0, 0, 0, 0.1)',
        'xl': '0 20px 25px rgba(0, 0, 0, 0.1)',
        '2xl': '0 25px 50px rgba(0, 0, 0, 0.15)',
      },
      transitionDuration: {
        '250': '250ms',
        '350': '350ms',
        '400': '400ms',
      },
      transitionTimingFunction: {
        'smooth': 'cubic-bezier(0.4, 0, 0.2, 1)',
      },
      fontSize: {
        'xs': ['12px', { lineHeight: '1.5' }],
        'sm': ['14px', { lineHeight: '1.6' }],
        'base': ['14px', { lineHeight: '1.6' }],
        'lg': ['18px', { lineHeight: '1.6' }],
        'xl': ['24px', { lineHeight: '1.4' }],
        '2xl': ['32px', { lineHeight: '1.3' }],
        '3xl': ['48px', { lineHeight: '1.2' }],
        '4xl': ['64px', { lineHeight: '1.1' }],
      },
      letterSpacing: {
        '0.05em': '0.05em',
        '0.08em': '0.08em',
        '0.1em': '0.1em',
        '0.12em': '0.12em',
        '0.15em': '0.15em',
        '0.2em': '0.2em',
        '0.25em': '0.25em',
        '0.3em': '0.3em',
        '0.35em': '0.35em',
      },
      fontWeight: {
        'light': '300',
        'normal': '400',
        'medium': '500',
        'semibold': '600',
        'bold': '700',
      },
    },
  },
  plugins: [],
};
