- generic [active] [ref=e1]:
  - generic [ref=e3]:
    - banner [ref=e4]:
      - generic [ref=e5]:
        - navigation "Primary navigation" [ref=e6]:
          - list [ref=e7]:
            - listitem [ref=e8]:
              - button "HIGHLIGHTS" [ref=e9]
            - listitem [ref=e10]:
              - button "FEMME" [ref=e11]
            - listitem [ref=e12]:
              - button "HOMME" [ref=e13]
            - listitem [ref=e14]:
              - button "SL PRODUCTIONS" [ref=e15]
            - listitem [ref=e16]:
              - link "Rive Droite" [ref=e17] [cursor=pointer]:
                - /url: https://www.ysl.com/fr-fr/rive-droite
                - generic [ref=e19]: Rive Droite
        - link "Saint Laurent" [ref=e21] [cursor=pointer]:
          - /url: https://www.ysl.com/fr-fr
          - img [ref=e23]
        - navigation "Secondary navigation" [ref=e28]:
          - list [ref=e29]:
            - listitem [ref=e30]:
              - link "LA MAISON" [ref=e31] [cursor=pointer]:
                - /url: https://www.ysl.com/fr-fr/collections/heritage
            - listitem [ref=e32]:
              - link "Boutiques" [ref=e33] [cursor=pointer]:
                - /url: https://www.ysl.com/fr-fr/stores
            - listitem [ref=e34]:
              - link "SERVICE CLIENT" [ref=e35] [cursor=pointer]:
                - /url: https://www.ysl.com/fr-fr/cp/client-service
            - listitem [ref=e36]:
              - link "SE CONNECTER" [ref=e37] [cursor=pointer]:
                - /url: https://www.ysl.com/fr-fr/signin
          - list [ref=e38]:
            - listitem [ref=e39]:
              - button "Search" [ref=e40] [cursor=pointer]:
                - img [ref=e41]
            - listitem [ref=e44]:
              - button "Cart" [ref=e45] [cursor=pointer]:
                - img [ref=e46]
    - main [ref=e49]:
      - generic [ref=e52]:
        - article [ref=e55]:
          - link [ref=e56] [cursor=pointer]:
            - /url: https://www.ysl.com/fr-fr/collections/spring-summer-26
            - figure [ref=e57]:
              - img "Homepage YSL > WS26 > Spring Summer 26 > Gifting Campaign" [ref=e58]
              - generic [ref=e59]:
                - heading "SPRING SUMMER 26" [level=2] [ref=e60]
                - heading "EXPLORER" [level=3] [ref=e61]
              - img [ref=e63]
        - article [ref=e67]:
          - link [ref=e68] [cursor=pointer]:
            - /url: https://www.ysl.com/fr-fr/collections/tangerine-temptation
            - figure [ref=e69]:
              - img "Image" [ref=e70]
              - generic [ref=e71]:
                - heading "TANGERINE TEMPTATION" [level=2] [ref=e72]
                - heading "DÉCOUVRIR" [level=3] [ref=e73]
        - generic [ref=e76]:
          - link [ref=e77] [cursor=pointer]:
            - /url: https://www.ysl.com/fr-fr/collections/women-summer-26-shop
            - figure [ref=e78]:
              - img "Image" [ref=e79]
              - generic [ref=e80]:
                - heading "PRÊT-À-PORTER" [level=2] [ref=e81]
                - heading "EXPLORER" [level=3] [ref=e82]
          - link [ref=e83] [cursor=pointer]:
            - /url: https://www.ysl.com/fr-fr/collections/women-summer-26-shoes-new-arrivals
            - figure [ref=e84]:
              - img "Image" [ref=e85]
              - generic [ref=e86]:
                - heading "CHAUSSURES" [level=2] [ref=e87]
                - heading "DÉCOUVRIR" [level=3] [ref=e88]
        - article [ref=e91]:
          - link [ref=e92] [cursor=pointer]:
            - /url: https://www.ysl.com/fr-fr/collections/men-spring-26-shop
            - figure [ref=e93]:
              - img "Homepage YSL > MS26 > Look Full 2" [ref=e94]
              - generic [ref=e95]:
                - heading "MEN’S SUMMER 26" [level=2] [ref=e96]
                - heading "EXPLORER" [level=3] [ref=e97]
        - article [ref=e100]:
          - link [ref=e101] [cursor=pointer]:
            - /url: https://www.ysl.com/fr-fr/rive-droite
            - figure [ref=e102]:
              - img "RD Block Home > Gifting Campaign" [ref=e103]
              - generic [ref=e104]:
                - heading "RIVE DROITE" [level=2] [ref=e105]
                - heading "DISCOVER" [level=3] [ref=e106]
        - article [ref=e109]:
          - link [ref=e111] [cursor=pointer]:
            - /url: https://saintlaurentproductions.ysl.com/
            - figure [ref=e112]:
              - generic [ref=e117]:
                - heading "SL PRODUCTIONS" [level=2] [ref=e118]
                - heading "Présente" [level=3] [ref=e119]
        - generic [ref=e122]:
          - navigation "Footer navigation" [ref=e123]:
            - list [ref=e124]:
              - listitem [ref=e125]:
                - generic [ref=e126]: Livraison
              - listitem [ref=e127]:
                - button "France € / fr" [ref=e128] [cursor=pointer]:
                  - generic [ref=e129]:
                    - generic [ref=e130]: France € / fr
                    - img [ref=e131]
            - list [ref=e133]:
              - listitem [ref=e134]:
                - link "SERVICE CLIENT" [ref=e135] [cursor=pointer]:
                  - /url: https://www.ysl.com/fr-fr/cp/client-service
              - listitem [ref=e136]:
                - link "livraisons & retours" [ref=e137] [cursor=pointer]:
                  - /url: https://www.ysl.com/fr-fr/cp/faq
              - listitem [ref=e138]:
                - link "SUIVRE VOTRE COMMANDE" [ref=e139] [cursor=pointer]:
                  - /url: https://www.ysl.com/fr-fr/track-order
              - listitem [ref=e140]:
                - link "+33 1 84 95 56 00" [ref=e141] [cursor=pointer]:
                  - /url: tel:+33184955600
              - listitem [ref=e142]:
                - link "RETOURNER VOTRE COMMANDE" [ref=e143] [cursor=pointer]:
                  - /url: https://www.ysl.com/fr-fr/return-order
              - listitem [ref=e144]:
                - button "PRENDRE UN RENDEZ-VOUS" [ref=e145] [cursor=pointer]:
                  - generic [ref=e146]:
                    - generic [ref=e147]: PRENDRE UN RENDEZ-VOUS
                    - img [ref=e148]
            - list [ref=e150]:
              - listitem [ref=e151]:
                - link "MENTIONS LÉGALES" [ref=e152] [cursor=pointer]:
                  - /url: https://www.ysl.com/fr-fr/legal/privacy-policy
              - listitem [ref=e153]:
                - button "PARAMÈTRES DES COOKIES" [ref=e154] [cursor=pointer]
              - listitem [ref=e155]:
                - link "POLITIQUE DES COOKIES" [ref=e156] [cursor=pointer]:
                  - /url: https://www.ysl.com/fr-fr/legal/cookie-policy
              - listitem [ref=e157]:
                - link "ACCESSIBILITÉ" [ref=e158] [cursor=pointer]:
                  - /url: https://www.ysl.com/fr-fr/legal/web-accessibility
              - listitem [ref=e159]:
                - link "CARRIÈRES" [ref=e160] [cursor=pointer]:
                  - /url: https://careers.kering.com/careers?filter_house=Saint+Laurent
            - list [ref=e161]:
              - listitem [ref=e162]:
                - button "S'INSCRIRE À LA NEWSLETTER" [ref=e163] [cursor=pointer]:
                  - generic [ref=e164]:
                    - generic [ref=e165]: S'INSCRIRE À LA NEWSLETTER
                    - img [ref=e166]
              - listitem [ref=e168]: Photographies retouchées
          - list "Navigation sociale" [ref=e169]:
            - listitem [ref=e170]:
              - link "facebook" [ref=e171] [cursor=pointer]:
                - /url: https://www.facebook.com/ysl
                - img [ref=e173]
            - listitem [ref=e175]:
              - link "instagram" [ref=e176] [cursor=pointer]:
                - /url: https://www.instagram.com/ysl/
                - img [ref=e178]
            - listitem [ref=e181]:
              - link "youtube" [ref=e182] [cursor=pointer]:
                - /url: https://www.youtube.com/ysl
                - img [ref=e184]
            - listitem [ref=e186]:
              - link "tiktok" [ref=e187] [cursor=pointer]:
                - /url: https://www.tiktok.com/@ysl
                - img [ref=e189]
  - alert [ref=e191]
  - dialog [ref=e192]:
    - generic [ref=e193]:
      - generic [ref=e194]: BIENVENUE SUR YSL.COM. VOUS NOUS VISITEZ DEPUIS France, SOUHAITEZ-VOUS RETOURNER à LA PAGE DU PAYS/RéGION OU à LA PAGE DE LA RéGION CORRESPONDANTE ?
      - generic [ref=e195]:
        - 'button "RESTER SUR : France" [ref=e196] [cursor=pointer]'
        - 'button "CONTINUER VERS : France" [ref=e197] [cursor=pointer]'